version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: edutrack_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: edutrack123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: