CREATE TABLE tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    grade DECIMAL(4,2) DEFAULT NULL,
    isCompleted BOOLEAN NOT NULL DEFAULT 0,
    dueDate DATE DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    subject_id INT NOT NULL,
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);